import React from 'react'


const TextoManifesto = () => {

    return (
        <section id="manifesto">
            <div className="manifesto container">
                <h1>Manifesto</h1>
            </div>
            <div className="textomanifesto">
                <p>
                    Chega de sofrer, chorar, reclamar e esperar pelo próximo governo. É hora de levantar a cabeça, construir nosso sonho de política junto e aproveitar as eleições para colocar a esperança revolucionária na mesa, tirando o povo das ilusões da ultra direita com sua política de morte, fome, desmatamento e violência policial. E sem cair na lama de uma esquerda que virou sistema, viciada em acordos com as elites/donos do poder e especialista em domar o povo para aceitar o roubo dos nossos recursos naturais, do nosso trabalho e dos nossos direitos.
                </p>
                <p>
                    É hora de trucar o sistema, as elites, ricos sem medo, sem domesticação, sem recuar e aceitar migalhas. Eles querem nos matar (mulheres, povo negro, indígenas, LGBT’s, povo pobre), mas isso é combustível para virar a mesa. Dizem os cristãos que aqui é o “Reino de Deus”. Se todos somos filhos de  Deus, todos somos donos dessa terra, da natureza, das águas, das frutas, da riqueza. O planeta é nosso e tudo o que foi produzido aqui é fruto do trabalho coletivo. Cada celular, lápis, roupa contou com a contribuição de milhares de pessoas. Pensemos no IPhone. A maior parte dele é metal, vidro e um pouco de plástico. Quantas pessoas recolheram, transportaram e fundiram nas fábricas os metais, vidros e plásticos? Quantas trabalharam para fazer microchips, telas e outros componentes? Quantas nas fábricas de montagem do aparelho? Quantas no transporte e logística, realizado em diferentes partes do mundo? E quantas na criação e planejamento dos aparelhos? Quantas no marketing e nas vendas online ou lojas físicas? Importante lembrar que toda a sociedade paga pelo impacto ambiental causado pela mineração, produção de vidro e o plástico (petróleo); sem contar o papelão das árvores e a gasolina para o transporte. Será que o lucro do IPhone deveria ir para os donos/acionistas da Apple? Ou para quem contribuiu com seu trabalho e a sociedade que pagou o preço ambiental ( mudança climática, falta de água, chuvas com inundações, secas, extinção de espécies animais e etc…) por isso? É tudo nossa família!
                </p>
                <p>
                    Além do desemprego, fome, Covid, violência e pobreza, estamos diante de uma tragédia ambiental que coloca toda a humanidade em risco. A Mudança Climática é violência contra a Mãe Terra e no Brasil o principal motivo é a pecuária. Os capitalistas transformaram árvores, frutos, terra, águas, pessoas indígenas e africanas, animais não humanos, mulheres….TUDO em coisa, objeto, mercadoria, produto, propriedade de uma elite europeia dominada por homens donos do poder. Os portugueses invadiram essa terra e dividiram com uma caneta o Brasil (que eles chamavam de paraíso) em meia dúzia de latifúndios. O que é nosso, de todos, virou propriedade privada DELES. E desde então fazem a gente trabalhar para comer, comer para trabalhar, trabalhando até morrer para ter talvez o mínimo de dignidade.
                </p>
                <p>
                A terra não pode ter dono, porque ela é a fonte da vida, um ser com vida própria, do qual dependemos e a quem devemos, antes de tudo, respeitar – se formos espertos. Mas para os colonizadores europeus respeitar a terra como um ser vivo não parece algo muito interessante, ou lucrativo. Respeitar a terra e todos que vivem nela reduz a margem de lucro e atrapalha o progresso.
                </p>
                <p>
                Esse sistema capitalista está em guerra com mãe natureza e com nossos parentes, animais não-humanos. Essa guerra permanente precisa acabar. Nós, humanos, somos parte da natureza, não somos inimigos dela. Somos homo sapiens sapiens, animais humanos que têm o direito e o dever de viver em harmonia com a mãe natureza. As plantas e bactérias existentes na mata e nas florestas transformam dióxido de carbono em O2, nos dão comida e ar puro. Essa naturofobia é uma ideologia reacionária inventada pelas elites para nos afastar da nossa própria natureza, da conexão sagrada que temos com as árvores, com a terra, com os rios, com as pedras, com o conjunto dos animais que coabitam este planeta conosco. Precisamos desenvolver a Consciência Animal, somos bichos e temos direito a viver livres, pisar o pé na terra, comer o fruto das árvores e beber águas limpas. Pela Libertação Animal, incluindo o animal humano! Chega de guerra com nossos parentes os animais não humanos, chega de coisificar os animais. Essa violência da pecuária causa o desmatamento, a poluição das águas, a invasão de terras indígenas/quilombolas, o efeito estufa e o assassinato desses animais dóceis transformados em objeto de lucro pelos capitalistas da carne que lucram com a morte desses seres e com as vendas de seus pedaços por aí.
                </p>
                <p>
                Desde que o capitalismo se espalhou pelo mundo, impondo à força o sistema das mercadorias, gerações de povos oprimidos lutaram contra o avanço desse sistema sobre suas terras e suas vidas. Nossos tataravós, bisavós sobreviveram, lutaram, resistiram, e graças a eles nós temos hoje mecanismos que limitam a ganância dos capitalistas com o objetivo de garantir mínima dignidade aos trabalhadores. Esses mecanismos são, por exemplo, os direitos trabalhistas, o salário mínimo, a licença maternidade, as cotas sociais e raciais, o seguro desemprego, a aposentadoria, além dos serviços públicos de infraestrutura, saúde e educação.
                </p>
                <p>
                Mas a elite burguesa bolou um novo plano de lucro: vender tudo que é do povo brasileiro para “investidores” (maioria estrangeiros); acabar com todas as leis que ajudam os trabalhadores e tb com a aposentadoria; extinguir o direito à saúde, educação, transporte, parques, água, natureza, moradia e transformar tudo isso em serviço pago e CARO. O nome é neoliberalismo.
                </p>
                <p>
                Esse plano vem sendo implementado no Brasil desde o governo FHC em 94. Mesmo com resistência, mudou a constituição dando poder aos bancos que ficaram livres para extorquir o povo, seja através de juros altos ou da dívida pública. Não é à toa que os lucros dos bancos batem recordes todos os anos. O PSDB assumiu a missão de ser o pai do neoliberalismo no Brasil, o office-boy da elite estrangeira, especialmente do imperialismo dos Estados Unidos - e transformando São Paulo no Tucanistão. A raiva do povo contra o neoliberalismo e os coronéis corruptos da política elegeu o Lula em 2002. Mas Lula resolveu fazer um governo de pacto com essas mesmas elites e coronéis, a famosa conciliação de classes. Distribuiu a migalha dessa renda para a população mais pobre - como dizia a minha avó: pro pobre, o pouco com Deus é muito - e enriqueceu os bancos “como nunca antes na história desse país”. Além disso, diminuiu os direitos de aposentadoria e mudou as regras - isenção de imposto, empréstimo com dinheiro público entre outras medidas - para facilitar a dominação, lucro e exploração de grandes corporações. Na educação fortaleceu grande conglomerados como a Anhanguera, a Kroton, a UNIP, através do Prouni; na exploração animal de comida processada, a JBS Friboi; na construção civil, especulação imobiliária e privatização do metrô, com a OAS, Camargo Correia, Andrade Gutierrez e Odebrecht. E a Petrobras vem sofrendo uma privatização “light” com poços de petróleo vendidos para agradar o mercado internacional.
                </p>
                <p>
                Mas toda essa mamata para a elite não foi suficiente, ela queria mais - queria o plano neoliberal implementado na versão “hardcore” e aí entra a função da Lava-jato. A corrupção no governo do PT virou uma desculpa da direita para dar um golpe institucional na Dilma e com isso facilitar a retirada de direitos do povo. O STF garantiu a prisão de Lula e proibiu sua candidatura e o PT nem tentou mobilizar a população, acreditando  que tudo se resolveria na eleição de 2018. Isso facilitou pro vampirão Temer congelar investimentos na saúde e educação por 20 anos, aprovar a reforma trabalhista e a lei da terceirização -arregaçando os trabalhadores-, uma nova lei de bases da educação -comandada pelos empresários da educação- e reforma do ensino médio -que acaba com a formação científica na escola pública. 
                </p>
                <p>
                Mas tudo isso ainda era pouco. Nas eleições presidenciais de 2018, o candidato preferido das elites, Geraldo Alckmin, não decolava. Bolsonaro, através de um discurso radical, anti-sistema e popular toma as periferias dos centros urbanos da maior parte do país. Com facada, fake news, apoio dos militares e de setores da imprensa, o ex-capitão mequetrefe se torna o candidato ideal para o plano das elites. Esse novo governo impõe uma nova reforma da previdência, corte nos recursos para educação, saúde, moradia e cultura, aumento de agrotóxicos; devastação ambiental generalizada através da agropecuária e da mineração, sempre ameaçando um golpe e organizando suas bases de ultra direita armada. O negacionismo da Covid resultou em mais de 600 mil mortes. Enquanto isso, a primeira atitude de Bolsonaro em março de 2020 foi mandar mais de 1 trilhão direto para os bancos, deixando o povo à míngua sem vacina, água, casa, comida e dignidade.
                </p>
                <p>
                Já existe uma ditadura, a Ditadura do capital, dos bancos e das elites - que garante eleições manipuladas pelo dinheiro e pela imprensa a cada 2/4 anos. Para impedir que essa ditadura se aprofunde, é preciso tirar o povo das mãos do Bolsonaro e não apenas vencer as eleições presidenciais. A esquerda precisa voltar a ser radical, revolucionária, transformadora - essa é a esperança que o povo quer e precisa e por isso acreditaram no Bolsonaro em 2018. Infelizmente, parte da esquerda  virou defensora do estado burguês, da ditadura dos ricos, de todo esse sistema, não acreditando ser possível fazer diferente. Ser de esquerda não é mais ser anticapitalista. No melhor dos casos, é resistir ao plano neoliberal da burguesia sem construir um plano para e com o povo, confiando na justiça ou nos setores “mais humanizados” das elites para reduzir os danos. No pior dos casos, é lacrar na internet usando racismo, machismo, LGTBfobia como performance para se afirmar, ganhar fama, dinheiro, cargos e influência dentro desse mesmo sistema.
                </p>
                <p>
                As eleições são uma oportunidade para conversar cara a cara com uma enorme quantidade de pessoas, encantar corações e mentes na perspectiva revolucionária - revelando que as propostas que minimamente podem garantir nossa sobrevivência neste planeta precisam ser construídas pelo poder popular e com a derrubada desse sistema de ditadura “democrática” do capital, da grana, das elites.
                </p>
                <p>
                Infelizmente neste momento o PSOL assumiu o pensamento da esquerda liberal, fugindo do enfrentamento com as elites e estreando um socialismo mansinho e domesticado. Mas o PSOL nasceu de uma ruptura histórica com o PT diante da sua traição à luta por direitos sociais e contra as elites. É hora de unir quem está no PSOL e está na pegada do radicalismo revolucionário, sem tempo pra conto de fadas, príncipe encantado e salvador da pátria.
                </p>
                <p>
                E qual é esse radicalismo revolucionário então? Ser radical não é ser intolerante, sectário ou sem noção da realidade, ser radical é ir à raiz dos problemas, é investigar a fundo o que está por trás e propor uma solução. É entender que a exploração capitalista só vai piorar, lascando ainda mais as nossas vidas. É entender que precisamos dizer em alto e bom som que nosso objetivo é acabar com o sistema capitalista! E colocar nossas propostas eleitorais concretas nesse rumo. Tomar o que é nosso, que está nas mãos dos ricos e das elites do capital financeiro, e proporcionar uma vida digna para todos. 
                </p>
                <p>
                Esperançar é verbo, ação concreta que transforma a realidade - queremos transformar essas ações abaixo em realidade, topa fazer junto?  
                </p>
            </div>
        </section>
    )
}

export default TextoManifesto